# Generated by Django 6.1 on 2026-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
