# Generated by Django 6.1 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_purchaseorder_stockmovement_related_purchase_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_margin_percent', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('labor_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('waste_buffer_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category_margin_overrides', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
