# Generated by Django 6.1 on 2026-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_loyaltysettings_customer_reward_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
