# Generated by Django 6.1 on 2026-08-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Fresh Cakes Made to Order', max_length=255)),
                ('hero_subtitle', models.TextField(default='Handcrafted desserts made with love and the finest ingredients.')),
                ('hero_image', models.CharField(blank=True, default='', max_length=500)),
                ('about_title', models.CharField(default='Our Story', max_length=255)),
                ('about_text', models.TextField(default='Rosaville Desserts began as a small home kitchen with a big dream — to bring joy through beautifully crafted cakes.')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_address', models.CharField(blank=True, default='', max_length=500)),
                ('business_hours', models.JSONField(blank=True, default=list)),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(default='#C9949B', max_length=7)),
                ('accent_color', models.CharField(default='#C97A85', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
