# Generated by Django 6.1 on 2026-08-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('storefront', '0003_alter_teammember_bio_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_cake_requests', to='operations.order'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Quoted', 'Quoted'), ('Confirmed', 'Confirmed'), ('In Production', 'In Production'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
