# Generated by Django 6.1 on 2026-08-14 20:07

import storefront.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_customcakeorder_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_subtitle',
            field=models.CharField(default='A tale of passion, family recipes, and the joy of creating sweet moments.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_values_items',
            field=models.JSONField(blank=True, default=storefront.models._default_about_values_items),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_values_title',
            field=models.CharField(default='Our Values', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='background_color',
            field=models.CharField(default='#FBF7F4', max_length=7),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='body_font',
            field=models.CharField(choices=[('Poppins', 'Poppins'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Nunito Sans', 'Nunito Sans'), ('Inter', 'Inter'), ('Work Sans', 'Work Sans')], default='Poppins', max_length=40),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='border_color',
            field=models.CharField(default='#E8D4D8', max_length=7),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='foreground_color',
            field=models.CharField(default='#3D2817', max_length=7),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='heading_font',
            field=models.CharField(choices=[('Playfair Display', 'Playfair Display'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Merriweather', 'Merriweather'), ('Libre Baskerville', 'Libre Baskerville'), ('DM Serif Display', 'DM Serif Display'), ('Lora', 'Lora')], default='Playfair Display', max_length=40),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_why_choose_items',
            field=models.JSONField(blank=True, default=storefront.models._default_home_why_choose_items),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_why_choose_subtitle',
            field=models.CharField(default="We're committed to excellence in every bite.", max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='home_why_choose_title',
            field=models.CharField(default='Why Choose Rosaville', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='muted_color',
            field=models.CharField(default='#F0D4D8', max_length=7),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='site_name',
            field=models.CharField(default='Rosaville Desserts', max_length=255),
        ),
    ]
