# Generated by Django 6.1 on 2026-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='in_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
