# Generated by Django 6.1 on 2026-08-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dessert_in_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(help_text='e.g. "August 2026"', max_length=100)),
                ('title', models.CharField(blank=True, help_text="Defaults to the dessert's name if left blank", max_length=255)),
                ('story', models.TextField(blank=True, help_text="Defaults to the dessert's description if left blank")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='catalog.dessert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
