# Generated by Django 6.1 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_specialofmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='batch_yield',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dessert',
            name='labor_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dessert',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dessert',
            name='target_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
